CREATE TABLE "metadata_config" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"value_chain_components" text[] NOT NULL,
	"processes" text[] NOT NULL,
	"lines_of_business" text[] NOT NULL,
	"business_segments" text[] NOT NULL,
	"geographies" text[] NOT NULL,
	"use_case_types" text[] NOT NULL,
	"activities" text[] DEFAULT '{}' NOT NULL,
	"source_types" text[] DEFAULT '{"rsa_internal","industry_standard","ai_inventory"}' NOT NULL,
	"use_case_statuses" text[] DEFAULT '{"Discovery","Backlog","In-flight","Implemented","On Hold"}' NOT NULL,
	"ai_ml_technologies" text[] DEFAULT '{"Machine Learning","Deep Learning","Natural Language Processing","Computer Vision","Predictive Analytics","Large Language Models","Reinforcement Learning","Rule-based Systems"}' NOT NULL,
	"data_sources" text[] DEFAULT '{"Policy Database","Claims Database","Customer Database","External APIs","Third-party Data","Real-time Feeds","Historical Data","Regulatory Data"}' NOT NULL,
	"stakeholder_groups" text[] DEFAULT '{"Underwriting Teams","Claims Teams","IT/Technology","Business Analytics","Risk Management","Compliance","Customer Service","External Partners"}' NOT NULL,
	"quadrants" text[] DEFAULT '{"Quick Win","Strategic Bet","Experimental","Watchlist"}' NOT NULL,
	"question_types" text[] DEFAULT '{"text","textarea","select","multi_select","radio","checkbox","number","date","email","url","company_profile","business_lines_matrix","smart_rating","multi_rating","percentage_allocation","percentage_target","ranking","currency","department_skills_matrix","business_performance","composite","dynamic_use_case_selector"}' NOT NULL,
	"response_statuses" text[] DEFAULT '{"started","in_progress","completed","abandoned"}' NOT NULL,
	"company_tiers" text[] DEFAULT '{"Small (<£100M)","Mid (£100M-£3B)","Large (>£3B)"}' NOT NULL,
	"market_options" text[] DEFAULT '{"Personal Lines","Commercial Lines","Specialty Lines","Reinsurance"}' NOT NULL,
	"process_activities" text,
	"scoring_model" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "response_sessions" (
	"id" varchar PRIMARY KEY NOT NULL,
	"questionnaire_id" varchar NOT NULL,
	"respondent_email" text NOT NULL,
	"respondent_name" text,
	"status" text DEFAULT 'started' NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"last_updated_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"progress_percent" integer DEFAULT 0 NOT NULL,
	"current_section_id" varchar,
	"current_question_id" varchar,
	"questionnaire_definition_path" text NOT NULL,
	"response_path" text,
	"total_score" real,
	"section_scores" jsonb,
	"questionnaire_version" text NOT NULL,
	"total_questions" integer NOT NULL,
	"answered_questions" integer DEFAULT 0 NOT NULL,
	"total_pages" integer DEFAULT 0 NOT NULL,
	"completed_pages" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "use_cases" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"problem_statement" text,
	"process" text NOT NULL,
	"value_chain_component" text,
	"line_of_business" text NOT NULL,
	"lines_of_business" text[],
	"business_segment" text NOT NULL,
	"geography" text NOT NULL,
	"use_case_type" text NOT NULL,
	"activity" text,
	"processes" text[],
	"activities" text[],
	"business_segments" text[],
	"geographies" text[],
	"revenue_impact" integer NOT NULL,
	"cost_savings" integer NOT NULL,
	"risk_reduction" integer NOT NULL,
	"broker_partner_experience" integer NOT NULL,
	"strategic_fit" integer NOT NULL,
	"data_readiness" integer NOT NULL,
	"technical_complexity" integer NOT NULL,
	"change_impact" integer NOT NULL,
	"model_risk" integer NOT NULL,
	"adoption_readiness" integer NOT NULL,
	"explainability_required" text,
	"customer_harm_risk" text,
	"data_outside_uk_eu" text,
	"third_party_model" text,
	"human_accountability" text,
	"ai_or_model" text,
	"risk_to_customers" text,
	"risk_to_rsa" text,
	"data_used" text,
	"model_owner" text,
	"rsa_policy_governance" text,
	"validation_responsibility" text,
	"informed_by" text,
	"business_function" text,
	"third_party_provided_model" text,
	"impact_score" real NOT NULL,
	"effort_score" real NOT NULL,
	"quadrant" text NOT NULL,
	"recommended_by_assessment" text,
	"manual_impact_score" real,
	"manual_effort_score" real,
	"manual_quadrant" text,
	"override_reason" text,
	"is_active_for_rsa" boolean DEFAULT false NOT NULL,
	"is_dashboard_visible" boolean DEFAULT false NOT NULL,
	"library_tier" text DEFAULT 'reference' NOT NULL,
	"activation_date" timestamp DEFAULT now(),
	"activation_reason" text,
	"deactivation_reason" text,
	"library_source" text DEFAULT 'rsa_internal' NOT NULL,
	"ai_inventory_status" text,
	"deployment_status" text,
	"last_status_update" timestamp,
	"primary_business_owner" text,
	"use_case_status" text DEFAULT 'Discovery',
	"key_dependencies" text,
	"implementation_timeline" text,
	"success_metrics" text,
	"estimated_value" text,
	"value_measurement_approach" text,
	"integration_requirements" text,
	"ai_ml_technologies" text[],
	"data_sources" text[],
	"stakeholder_groups" text[],
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
