import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { Response } from 'express';
import { format } from 'date-fns';
import { APP_CONFIG } from '@shared/constants/app-config';

interface RSABranding {
  primaryColor: string;
  secondaryColor: string;
  logoPath?: string;
  fontFamily: string;
}

interface ExportOptions {
  title: string;
  subtitle?: string;
  author: string;
  includeQR?: boolean;
  includeTimestamp?: boolean;
  branding?: RSABranding;
}

export class PDFExportService {
  private static readonly RSA_BRANDING: RSABranding = {
    primaryColor: APP_CONFIG.PDF.BRAND_COLORS.PRIMARY,
    secondaryColor: APP_CONFIG.PDF.BRAND_COLORS.SECONDARY,
    fontFamily: APP_CONFIG.PDF.FONTS.PRIMARY,
  };

  private static readonly PAGE_MARGINS = {
    top: APP_CONFIG.PDF.MARGINS.TOP,
    bottom: APP_CONFIG.PDF.MARGINS.BOTTOM,
    left: APP_CONFIG.PDF.MARGINS.LEFT,
    right: APP_CONFIG.PDF.MARGINS.RIGHT,
  };

  /**
   * Create a new PDF document with RSA branding
   */
  static createDocument(options: ExportOptions): any {
    const doc = new PDFDocument({
      size: 'A4',
      margins: this.PAGE_MARGINS,
      info: {
        Title: options.title,
        Author: options.author,
        Subject: 'RSA AI Use Case Value Framework',
        Keywords: 'RSA, AI, Assessment, Use Cases',
        Creator: 'RSA AI Framework',
        Producer: 'RSA Insurance',
      },
    });

    return doc;
  }

  /**
   * Add RSA header to each page
   */
  static addHeader(doc: any, title: string, pageNumber: number): void {
    const { primaryColor } = this.RSA_BRANDING;
    
    // Header background
    doc.rect(0, 0, doc.page.width, 60)
       .fill(primaryColor);

    // RSA Logo area (placeholder for now)
    doc.rect(20, 10, 40, 40)
       .fill('#FFFFFF');
    
    doc.fontSize(8)
       .fillColor('#005DAA')
       .text('RSA', 25, 25);

    // Title
    doc.fontSize(14)
       .fillColor('#FFFFFF')
       .text(title, 80, 25, { width: doc.page.width - 160 });

    // Page number
    doc.fontSize(10)
       .fillColor('#FFFFFF')
       .text(`Page ${pageNumber}`, doc.page.width - 80, 25, { align: 'right' });

    // Reset position after header
    doc.y = 80;
  }

  /**
   * Add RSA footer to each page
   */
  static addFooter(doc: any): void {
    const footerY = doc.page.height - 60;
    const { primaryColor } = this.RSA_BRANDING;
    
    doc.rect(0, footerY, doc.page.width, 60)
       .fill('#F8F9FA');

    doc.fontSize(8)
       .fillColor(primaryColor)
       .text('RSA AI Use Case Value Framework - Confidential', 20, footerY + 20)
       .text(format(new Date(), 'PPP'), 20, footerY + 35)
       .text('Generated by RSA Digital Innovation', doc.page.width - 200, footerY + 20, { align: 'right' });
  }

  /**
   * Add section header with RSA styling
   */
  static addSectionHeader(doc: any, title: string, level: number = 1): void {
    const fontSize = level === 1 ? 16 : 14;
    const { primaryColor } = this.RSA_BRANDING;
    
    doc.moveDown(1)
       .fontSize(fontSize)
       .fillColor(primaryColor)
       .text(title, { underline: true });
    
    doc.moveDown(0.5);
  }

  /**
   * Add data table with RSA styling
   */
  static addTable(doc: any, headers: string[], rows: string[][], options?: {
    columnWidths?: number[];
    alternateRowColor?: boolean;
  }): void {
    const { primaryColor } = this.RSA_BRANDING;
    const startY = doc.y;
    const tableWidth = doc.page.width - this.PAGE_MARGINS.left - this.PAGE_MARGINS.right;
    const columnWidths = options?.columnWidths || headers.map(() => tableWidth / headers.length);
    const rowHeight = 25;

    // Header row
    let currentX = doc.x;
    doc.rect(currentX, startY, tableWidth, rowHeight)
       .fill(primaryColor);

    headers.forEach((header, i) => {
      doc.fontSize(10)
         .fillColor('#FFFFFF')
         .text(header, currentX + 5, startY + 7, { 
           width: columnWidths[i] - 10,
           align: 'left'
         });
      currentX += columnWidths[i];
    });

    // Data rows
    let currentY = startY + rowHeight;
    rows.forEach((row, rowIndex) => {
      const fillColor = options?.alternateRowColor && rowIndex % 2 === 1 ? '#F8F9FA' : '#FFFFFF';
      
      doc.rect(doc.x, currentY, tableWidth, rowHeight)
         .fill(fillColor)
         .stroke('#E5E5E5');

      currentX = doc.x;
      row.forEach((cell, i) => {
        doc.fontSize(9)
           .fillColor('#333333')
           .text(cell, currentX + 5, currentY + 7, { 
             width: columnWidths[i] - 10,
             align: 'left'
           });
        currentX += columnWidths[i];
      });
      
      currentY += rowHeight;
    });

    doc.y = currentY + 10;
  }

  /**
   * Add QR code for digital access
   */
  static async addQRCode(doc: any, url: string, x: number, y: number): Promise<void> {
    try {
      const qrBuffer = await QRCode.toBuffer(url, {
        width: 80,
        margin: 1,
        color: {
          dark: '#005DAA',
          light: '#FFFFFF'
        }
      });
      
      doc.image(qrBuffer, x, y, { width: 80, height: 80 });
      
      doc.fontSize(8)
         .fillColor('#666666')
         .text('Scan for digital access', x - 10, y + 85, { width: 100, align: 'center' });
    } catch (error) {
      console.error('Failed to generate QR code:', error);
    }
  }

  /**
   * Stream PDF to response
   */
  static streamToResponse(doc: any, res: Response, filename: string): void {
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    
    doc.pipe(res);
    doc.end();
  }

  /**
   * Add cover page with RSA branding
   */
  static addCoverPage(doc: any, options: {
    title: string;
    subtitle?: string;
    generatedFor?: string;
    date?: Date;
  }): void {
    const { primaryColor } = this.RSA_BRANDING;
    
    // Full-page RSA blue background
    doc.rect(0, 0, doc.page.width, doc.page.height)
       .fill(primaryColor);

    // RSA Logo placeholder (large)
    doc.rect(doc.page.width / 2 - 50, 100, 100, 100)
       .fill('#FFFFFF');
    
    doc.fontSize(24)
       .fillColor(primaryColor)
       .text('RSA', doc.page.width / 2 - 20, 140);

    // Main title
    doc.fontSize(28)
       .fillColor('#FFFFFF')
       .text(options.title, 60, 250, { 
         width: doc.page.width - 120,
         align: 'center'
       });

    // Subtitle
    if (options.subtitle) {
      doc.fontSize(16)
         .fillColor('#E8F4FD')
         .text(options.subtitle, 60, 300, { 
           width: doc.page.width - 120,
           align: 'center'
         });
    }

    // Generated for
    if (options.generatedFor) {
      doc.fontSize(12)
         .fillColor('#FFFFFF')
         .text(`Generated for: ${options.generatedFor}`, 60, 400, { 
           width: doc.page.width - 120,
           align: 'center'
         });
    }

    // Date
    const date = options.date || new Date();
    doc.fontSize(12)
       .fillColor('#E8F4FD')
       .text(format(date, 'PPPP'), 60, 450, { 
         width: doc.page.width - 120,
         align: 'center'
       });

    // Add new page for content
    doc.addPage();
  }
}